# Generated by Django 4.1 on 2022-12-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_var', models.IntegerField(null=True)),
                ('jumlah_fungsi', models.IntegerField(null=True)),
            ],
        ),
    ]
