# Generated by Django 4.1 on 2023-04-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icungapp', '0006_alter_dataproses_options_dataproses_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproses',
            name='token',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
